# Generated by Django 3.2.18 on 2023-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_auto_20230515_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="jpgImage",
            field=models.ImageField(blank=True, null=True, upload_to="JPGs/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
