# Generated by Django 3.2.18 on 2023-05-19 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_auto_20230518_1002"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="jpgImage",
            new_name="jpg_image",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="pngImage",
            new_name="png_image",
        ),
    ]
