# Generated by Django 3.2.18 on 2023-05-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0006_auto_20230519_0936"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="images.image",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
