name: React CI with Testing-Library

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set working directory
        run: cd frontend

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Run tests
        run: |
          cd frontend
          yarn test